export const GET_USERS_LIST_REQUEST = "GET_USERS_LIST_REQUEST";
export const GET_USERS_LIST_SUCCESS = "GET_USERS_LIST_SUCCESS";
export const GET_USERS_LIST_FAIL = "GET_USERS_LIST_FAIL";

export const GET_ALBUMS_LIST_REQUEST = "GET_ALBUMS_LIST_REQUEST";
export const GET_ALBUMS_LIST_SUCCESS = "GET_ALBUMS_LIST_SUCCESS";
export const GET_ALBUMS_LIST_FAIL = "GET_ALBUMS_LIST_FAIL";

export const GET_PHOTOS_LIST_REQUEST = "GET_PHOTOS_LIST_REQUEST";
export const GET_PHOTOS_LIST_SUCCESS = "GET_PHOTOS_LIST_SUCCESS";
export const GET_PHOTOS_LIST_FAIL = "GET_PHOTOS_LIST_FAIL";
